### ISSUE TITLE
[feature/build-logic] build-logic 구성 작업 진행

### ISSUE THREAD

**Issue by hanseul-Choi** [hanseul-Choi/NewDeps#3]
## Description
- gradle 관리를 build-logic에 맞추어 관리하는 구조로 변경합니다.

## To-do
- [x] build-logic 디렉토리 계층 구조 생성
- [x] build-logic 클래스 생성 및 적용
- [x] build-logic 정상 적용되었는지 테스트

**Comment by hanseul-Choi** [comment]
build-logic 구성 완료
- Application
- Library
- Compose
- Kotlin
